import type { BankInfo } from "@/types/photomanage/transaction";

export const BANKS: BankInfo[] = [
  { code: "NH", name: "NH농협", type: "bank" },
  { code: "KAKAO", name: "카카오뱅크", type: "bank" },
  { code: "KB", name: "KB국민", type: "bank" },
  { code: "TOSS", name: "토스뱅크", type: "bank" },
  { code: "SHINHAN", name: "신한", type: "bank" },
  { code: "WOORI", name: "우리", type: "bank" },
  { code: "IBK", name: "IBK기업", type: "bank" },
  { code: "HANA", name: "하나", type: "bank" },
  { code: "SAEMAEUL", name: "새마을", type: "bank" },
  { code: "BUSAN", name: "부산", type: "bank" },
  { code: "IM", name: "iM뱅크(대구)", type: "bank" },
  { code: "KBANK", name: "케이뱅크", type: "bank" },
  { code: "SHINHYUP", name: "신협", type: "bank" },
  { code: "POST", name: "우체국", type: "bank" },
  { code: "SC", name: "SC제일", type: "bank" },
  { code: "GYEONGNAM", name: "경남", type: "bank" },
  { code: "GWANGJU", name: "광주", type: "bank" },
  { code: "SUHYUP", name: "수협", type: "bank" },
  { code: "JEONBUK", name: "전북", type: "bank" },
  { code: "SAVINGS", name: "저축은행", type: "bank" },
  { code: "JEJU", name: "제주", type: "bank" },
  { code: "CITI", name: "시티", type: "bank" },
  { code: "KDB", name: "KDB산업", type: "bank" },
  { code: "SANLIM", name: "산림조합", type: "bank" },
  { code: "SBI", name: "SBI저축은행", type: "bank" },
  { code: "BOA", name: "BOA", type: "bank" },
  { code: "CHINA", name: "중국", type: "bank" },
  { code: "HSBC", name: "HSBC", type: "bank" },
  { code: "ICBC", name: "중국공상", type: "bank" },
  { code: "DEUTSCHE", name: "도이치", type: "bank" },
  { code: "JPMORGAN", name: "JP모건", type: "bank" },
  { code: "BNP", name: "BNP파리바", type: "bank" },
  { code: "CCB", name: "중국건설", type: "bank" },
];

export const SECURITIES: BankInfo[] = [
  { code: "TOSS_SEC", name: "토스증권", type: "securities" },
  { code: "KAKAO_SEC", name: "카카오페이증권", type: "securities" },
  { code: "MIRAE", name: "미래에셋", type: "securities" },
  { code: "KIWOOM", name: "키움", type: "securities" },
  { code: "KOREA_INV", name: "한국투자", type: "securities" },
  { code: "SHINHAN_SEC", name: "신한투자", type: "securities" },
  { code: "SAMSUNG_SEC", name: "삼성증권", type: "securities" },
  { code: "KB_SEC", name: "KB증권", type: "securities" },
  { code: "NG_SEC", name: "NG투자", type: "securities" },
  { code: "YUANTA", name: "유안타", type: "securities" },
  { code: "DAISHIN", name: "대신", type: "securities" },
  { code: "IBK_SEC", name: "IBK투자", type: "securities" },
  { code: "HANA_SEC", name: "하나증권", type: "securities" },
  { code: "HANWHA", name: "한화투자", type: "securities" },
  { code: "EUGENE", name: "유진투자", type: "securities" },
  { code: "IM_SEC", name: "아이엠증권", type: "securities" },
  { code: "KYOBO", name: "교보", type: "securities" },
  { code: "MERITZ", name: "메리츠증권", type: "securities" },
  { code: "SK_SEC", name: "SK", type: "securities" },
  { code: "LS_SEC", name: "LS", type: "securities" },
  { code: "HYUNDAI_SEC", name: "현대차증권", type: "securities" },
  { code: "DB_SEC", name: "DB증권", type: "securities" },
  { code: "WOORI_SEC", name: "우리투자증권", type: "securities" },
  { code: "SHINYOUNG", name: "신영", type: "securities" },
  { code: "DAOL", name: "다올투자증권", type: "securities" },
  { code: "CAPE", name: "케이프투자", type: "securities" },
  { code: "BNK_SEC", name: "BNK투자", type: "securities" },
  { code: "BOOKOOK", name: "부국", type: "securities" },
  { code: "SANGSANGIN", name: "상상인증권", type: "securities" },
];

export const ALL_FINANCIAL_INSTITUTIONS: BankInfo[] = [...BANKS, ...SECURITIES];
